### PR TITLE
Fix/775 fix redis not cache an excessive amount

### PR DESCRIPTION
**Pull request by Gurrit**

### CODE REVIEW

**Comment by Portals** [comment]
Can't get this to work :(

**Comment by Portals** [comment]
Should I merge this into `refactor`? @Gurr1

**Comment by Gurr1** [comment]
Yeah, i thought this had been merged...

Merge it into the refactoring branch and I'll try to fix it as soon as possible

**Comment by hulthe** [comment]
image
pls :heart:

**Comment by Portals** [comment]
@Gurr1 @rosengrenen and I resolved some issues with gradle, but could you please take a look at it again? cause we can't get it to work

**Comment by Gurr1** [comment]
I'll take a look as soon as I have time

**Comment by Portals** [comment]
Closing since you cannot access `/api/internal` anymore with an API key.

**Pull request closed without merging**
