### PR TITLE
Only allow post to be deleted if they are not used

### PR DESCRIPTION
**Pull request by molleer**
I saw that @Portals had solved the frontend part of #692 but there was nothing in the backend preventing the client from deleting a post which is in use.

### CODE REVIEW

**Comment by Portals** [comment]
Why is this issue relevant? In #692 I state:

>Show that it isn't possible in the frontend

**Comment by molleer** [comment]
Since the delete button is hidden in the frontend if the post is in use, I thought that it was a way of showing that the post cannot be deleted. Therefore the frontend part of #692 was already fixed

**Comment by Portals** [comment]
It is not hidden? 
image

**Comment by molleer** [comment]
I must have missed it 😅 
I can disable the delete button if the post is used and add a tooltop which says something like "You cannot delete this post since it is in use"

**Comment by Portals** [comment]
Missed entirely that this was a PR lol

**Comment by Portals** [comment]
Not sure if Tooltip actually works, but disabling it might be a thing to do!

**Comment by Portals** [comment]
Would you mind fixing the build in this PR aswell?

**Comment by molleer** [comment]
You are only using DigitCRUD and you are not storeing the data in a useState hook, so it is impossible to customize the Posts view under use-cases. This is horrible, I have to change DigitCRUD in RDC to be able of doing what I want to do :cry:.

**Comment by Portals** [comment]
Nah just use `canDelete` in `DigitCRUD` and add a text explaining why the post isn't deleteable.

**Comment by Portals** [comment]
>This is horrible
Don't agree. This is by design.

**Comment by molleer** [comment]
Aight, sorry for missing that ... as well
And sorry for shitting on you code :disappointed:

**Comment by Portals** [comment]
@Gurr1 Merge? Everything works on my machine.

**Comment by Gurr1** [comment]
Sure, looks fine to me

**Pull request merged**
