### PR TITLE
License under the GNU AGPL

### PR DESCRIPTION
**Pull request by hulthe**
If this project is going to be used in production by the IT student division, it should probably not be proprietary :)

So this is my suggestion for a FOSS license.

### CODE REVIEW

**Comment by hulthe** [comment]
I'm not allowed to request reviewers, but any license change should be approved by all copyright holders of the source code:

@Portals 
@Gurr1
@NeonSky
@cajoho99 
@Sponken 
@molleer 
@Dr-Horv

**Comment by feffes** [comment]
It might already do this idk but just to be sure:
AGPL requires that any distribution or "serving" of the program to the user must adequately signal where the user can acquire the source code. So if it doesn't already exist there should be a link to this github page somewhere easily accessible on the web page.

**Comment by Dr-Horv** [comment]
@feffes where does it? I think you're speaking about section 13? As I understand it that if you modify the program you need to provide the source code. It's to close the SaaS-loophole of GPL3. https://opensource.com/article/17/1/providing-corresponding-source-agplv3-license

**Comment by Dr-Horv** [comment]
@hulthe Why AGPL? 

I'd suggest for simplicity, just use one of the most used licenses, MIT if we want it fully open or GPLv3 regarding improvements

**Comment by hulthe** [comment]
@Dr-Horv My reason for suggesting this license is that the AGPLv3 and GPLv3 are nearly identical, and wouldn't make any practical difference for the our use case. The reason I didn't suggest a more permissive license is simply personal preference.

@feffes Adding a link to the source code is a good idea regardless :)

**Comment by Gurr1** [comment]
Im going to merge this. 
But I can agree that the licence might be a bit too corporate for this project. 
However, since this project right now is without licence, I see this as the best choice right now.

**Pull request merged**
