### PR TITLE
added actuator for monitoring. '/api/actuator/health' is available.

### PR DESCRIPTION
**Pull request by kackey0-1**
added actuator for monitoring. now '/api/actuator/health' is available. please review this change. #747

### CODE REVIEW

**Comment by kackey0-1** [comment]
I hope I understood what you mentioned. please review the changes.

**Comment by Gurr1** [comment]
I'd prefer this endpoint to be under /admin, easiest way to do this is probably to just set the context path under management in application.yml

**Comment by kackey0-1** [comment]
I reverted WebSecurityConfig.java, then I added endpoint setting in application.yml

**Review by Portals — APPROVED** [review]
@Gurr1 you have the final say

**Comment by Portals** [comment]
Doing large refactoring to the project, and this PR will probably clash a bit with those changes. So for now I'm going to close this. But once again, thank you for your PR!

**Pull request closed without merging**
